import type { CommandGenInput } from '../types.js';

export function generateBackupCommands(input: CommandGenInput): {
  script: string;
  steps: { title: string; command: string; explanation: string }[];
} {
  const { os, sourcePath, outputDir, archiveName = 'backup', discDevice = '/dev/sr0', includeCloud = true } = input;

  const steps: { title: string; command: string; explanation: string }[] = [];

  if (os === 'windows') {
    // Windows PowerShell Script
    steps.push({
      title: '1. 7-Zipによる圧縮・4GB分割・パリティ付与',
      command: `& "C:\\Program Files\\7-Zip\\7z.exe" a -mx9 -mrr5% "${outputDir}\\${archiveName}.7z" "${sourcePath}" -v4095m`,
      explanation: '7-Zipで最高圧縮率(-mx9)・5%リカバリレコード(-mrr5%)を付与し、FAT32/UDF互換のため4095MB単位で分割保存します。',
    });

    steps.push({
      title: '2. SHA-256ハッシュリストの生成',
      command: `Get-FileHash "${outputDir}\\${archiveName}.7z.*" -Algorithm SHA256 | Export-Csv -Path "${outputDir}\\${archiveName}.hashlist.csv" -NoTypeInformation`,
      explanation: '書き込み前のデータ全分割ファイルのハッシュ値を記録します。',
    });

    steps.push({
      title: '3. クラウドバックアップ同期 (rclone)',
      command: `rclone sync "${sourcePath}" "remote:BackupBucket/${archiveName}" --progress --transfers 4`,
      explanation: '暗号化クラウドストレージへ最新ファイルを同期します。',
    });

    const script = steps.map((s) => `# ${s.title}\n# ${s.explanation}\n${s.command}\n`).join('\n');

    return { script, steps };
  }

  // Linux / macOS Shell Script
  steps.push({
    title: '1. 7-Zip圧縮と4GB分割アーカイブ作成',
    command: `7z a -mx9 -mrr5% "${outputDir}/${archiveName}.7z" "${sourcePath}" -v4095m`,
    explanation: '7-Zipで高効率圧縮と5%のパリティデータ(リカバリ領域)を付与し、4095MB上限に分割します。',
  });

  steps.push({
    title: '2. SHA-256ハッシュリストの作成',
    command: `cd "${outputDir}" && shasum -a 256 ${archiveName}.7z.* > ${archiveName}.hashlist`,
    explanation: '後からの破損・ビットロット検証のため、全パーツのSHA-256チェックサムを保存します。',
  });

  steps.push({
    title: '3. Blu-ray書き込み用ISOイメージ作成',
    command: `mkisofs -V "${archiveName}" -J -r -o "${outputDir}/${archiveName}.iso" "${outputDir}/${archiveName}".7z.* "${outputDir}/${archiveName}.hashlist"`,
    explanation: '7zアーカイブとハッシュファイルをまとめたBlu-ray焼付け用ISOを作成します。',
  });

  steps.push({
    title: '4. Blu-rayディスクへのライティングと同時にベリファイ',
    command: `growisofs -dvd-compat -Z ${discDevice}="${outputDir}/${archiveName}.iso"`,
    explanation: `${discDevice} ドライブにBlu-rayディスクをセットし、ISOをファイナライズしてライティングします。`,
  });

  steps.push({
    title: '5. ディスクの読み出しハッシュベリファイ検証',
    command: `mkdir -p /tmp/bluray_mount && sudo mount ${discDevice} /tmp/bluray_mount\ncd /tmp/bluray_mount && shasum -a 256 -c ${archiveName}.hashlist\nsudo umount /tmp/bluray_mount`,
    explanation: '書き込まれたBlu-rayメディアをマウントし、ハッシュ値が一致するか整合性を完全手動検証します。',
  });

  if (includeCloud) {
    steps.push({
      title: '6. (任意) 暗号化クラウドストレージ同期',
      command: `rclone sync "${sourcePath}" "b2:my-encrypted-backup/${archiveName}" --fast-list --progress`,
      explanation: 'Backblaze B2 または AWS S3 Glacier へ二次オフサイトコピーを自動同期します。',
    });
  }

  const script = `#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# バックアップ自動化スクリプト (Generated by backup-advisor-mcp)
# OS: ${os.toUpperCase()} | Source: ${sourcePath}
# ==============================================================================

` + steps.map((s) => `# ${s.title}\n# ${s.explanation}\n${s.command}\n`).join('\n');

  return { script, steps };
}
